language: java
jdk: 
  - oraclejdk8
  - openjdk8
  
services:
  - redis-server

script: jdk_switcher use oraclejdk8

install: ./mvnw -U install --quiet -DskipTests=true -P bootstrap
script: ./mvnw clean test -P bootstrap


